### ISSUE TITLE
problem about output log file

### ISSUE THREAD

**Issue by Jadaeu** [NUStreaming/BoB#6]
![image](https://github.com/NUStreaming/BoB/assets/105416501/26be581c-825f-459a-8325-563f27840024)
Hello author, I am very interested in your work. And I am actively running the source code. At present, the output log file I get has only 20 seconds of data, but there are 60 seconds in the paper. May I ask the author how to solve this problem?

**Comment by HoustonHuff** [comment]
Hello,

I don't know if you're stuck on this problem, but check the "autoclose" values of receiver_pyinfer.json and sender_pyinfer.json; try changing them to 60 if they are not already.

**Comment by Jadaeu** [comment]
> Hello,
> 
> I don't know if you're stuck on this problem, but check the "autoclose" values of receiver_pyinfer.json and sender_pyinfer.json; try changing them to 60 if they are not already.
Got it. Thanks!

**Comment by Jadaeu** [comment]
> Hello,
> 
> I don't know if you're stuck on this problem, but check the "autoclose" values of receiver_pyinfer.json and sender_pyinfer.json; try changing them to 60 if they are not already.

hello,  sir HoustonHuff, have you tried to train the BoB model with self-make dataset? Currently i want to train the BoB model with my dataset, but i tried a lot still can't achieve BoB's training.. Do you have some ideas to share? Looking forward to you any reply!

**Comment by HoustonHuff** [comment]
> > Hello,
> > I don't know if you're stuck on this problem, but check the "autoclose" values of receiver_pyinfer.json and sender_pyinfer.json; try changing them to 60 if they are not already.
> 
> hello, sir HoustonHuff, have you tried to train the BoB model with self-make dataset? Currently i want to train the BoB model with my dataset, but i tried a lot still can't achieve BoB's training.. Do you have some ideas to share? Looking forward to you any reply!

Hello, in my own work I've made some progress in creating a live model training BWE on BoB based on Gemini's model pre-training method. For a while I was struggling to find any sort of convergence in the training, but then I discovered that in tc_profiles/tc_policy.sh the namespace script governing the dynamic network bandwidth actually uses an optional burst argument, meaning that rather than streaming bits at a static rate in the leaky bucket fashion the network holds onto groups of bits and sends them out in bursty groups. I found that when I removed the burst argument the bandwidth became stable enough for the model to reach convergence in my online training, though I still wasn't able to achieve signs of learning from BoB's own RL agent in Bandwidth_BoB.py, so my guess is that's a separate issue. I hope this helps.

**Comment by Jadaeu** [comment]
> > > Hello,
> > > I don't know if you're stuck on this problem, but check the "autoclose" values of receiver_pyinfer.json and sender_pyinfer.json; try changing them to 60 if they are not already.
> > 
> > 
> > hello, sir HoustonHuff, have you tried to train the BoB model with self-make dataset? Currently i want to train the BoB model with my dataset, but i tried a lot still can't achieve BoB's training.. Do you have some ideas to share? Looking forward to you any reply!
> 
> Hello, in my own work I've made some progress in creating a live model training BWE on BoB based on Gemini's model pre-training method. For a while I was struggling to find any sort of convergence in the training, but then I discovered that in tc_profiles/tc_policy.sh the namespace script governing the dynamic network bandwidth actually uses an optional burst argument, meaning that rather than streaming bits at a static rate in the leaky bucket fashion the network holds onto groups of bits and sends them out in bursty groups. I found that when I removed the burst argument the bandwidth became stable enough for the model to reach convergence in my online training, though I still wasn't able to achieve signs of learning from BoB's own RL agent in Bandwidth_BoB.py, so my guess is that's a separate issue. I hope this helps.

I see, Thank you for your help!
